### ISSUE TITLE
Generated type class directory permissions

### ISSUE THREAD

**Issue by fantomas662** [overblog/GraphQLPhpGenerator#24]
Please consider using the default permissions (`0777`) when creating directories for generated type classes. Using `0775` causes permission errors when the classes need to be deleted and recreated under a different user (e.g. by `CompileCacheWarmer` from `GraphQLBundle`).

`Failed to remove file "<snip>/dev/overblog/graphql-bundle/__definitions__/FooBarType.php": unlink(<snip>/overblog/graphql-bundle/__definitions__/FooBar.php): Permission denied.`

https://github.com/overblog/GraphQLPhpGenerator/blob/f6881be5b469213b4d55be947ce2ce6fe946107b/src/Generator/AbstractTypeGenerator.php#L364

This can happen often during Symfony app development where the cache is populated automatically both via `bin/console` (runs under `root` in docker) and the webserver (runs under `www-data`) when some files are changed.

Looking at the cache directory, `overblog/graphql-bundle/__definitions__` is the only path that has `0755` permissions. Everything else (doctrine, pools, containers, twig, etc.) has `0777`.

**Comment by mcg-web** [comment]
Hi, Maybe we should just make this configurable ?

**Comment by Fantomas-7** [comment]
I guess it wouldn't hurt to have it configurable as long as such configuration can be defined in `GraphQLBundle` (and it should probably default to `0777` so it's consistent with other cache dirs).
