### ISSUE TITLE
Generating resolve functions

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLPhpGenerator#25]
After I recently switched to [GraphQL Schema Language](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/graphql-schema-language.md) + custom [ResolverMaps](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/resolver-map.md) setup I now want to optimize the GraphQL layer.

Currently one of the bottlenecks is the usage of PropertyAccess as the default resolver. At the moment all generated GraphQL types have `'resolve' => null,` for all their fields. For those fields that just need to access an array or call a getter on the $rootValue I'd like to generate closures into the generated types. These closures would mostly look like this:

```php
// Resolver for the 'id' field
function ($rootValue) {
    return $rootValue->getId();
}
```

Now I'm able to use custom compiler pass to hijack the the config that is used as input for `overblog/graphql-php-generator`. I just need to know what I should put into the config array as value of the `'resolve'` key to generate the code I want. Can you give me any tips? I can write a PR for documentation.

EDIT: Yes I could of course add another ResolverMap for those fields and handle it there with `$rootValue->{'get'.$field}()` or something but I don't like dynamic method calls and since there already is a generated class, there is no reason not to improve the generated code. Using ResolverMap for this would be slower anyway.

EDIT2: Delving into the code maybe ExpressionLanguage would compile to what I want? The generator seems to have some support for it. I guess I'll try that.

**Comment by mcg-web** [comment]
I next way is just to override default resolver to use your custom default resolver [see this issue for the howto](https://github.com/overblog/GraphQLBundle/issues/380#issuecomment-420518626)

**Comment by enumag** [comment]
Yeah I know but I'd much prefer to generate this code - it would be faster that way.

**Comment by mcg-web** [comment]
The expression language is the best way to go right now.

**Comment by enumag** [comment]
Ok I tried it with ExpressionLanguage. It should be pretty easy that way and normally it would work just fine. The problem is that the `TypeGenerator` detects the expression with [this](https://github.com/overblog/GraphQLPhpGenerator/blob/master/src/Generator/AbstractTypeGenerator.php#L89). However it is not possible to put `Expression` instances into the `%overblog_graphql_types.config%` parameter because Symfony DI will try to resolve them and throw an exception. So I have no way to add the expressions into the config in my compiler pass.

**Comment by mcg-web** [comment]
an expression is just a string with the trigger `@=` in config ex: `@=value`
